### ISSUE TITLE
addding script for install unbound....

### ISSUE THREAD

**Issue by iamspa** [simonclausen/dnscrypt-autoinstall#97]
hello sir, can you add script for install unbound, so unbound can use dnscrypt for resolving dns and other computer konek to unbound for dns resolver

**Comment by darkerego** [comment]
Install unbound with apt, yum or whatever you use. Than edit the configuration file (/etc/unbound/unbound.conf usually):


  ```
  auto-trust-anchor-file: "/var/lib/unbound/root.key"
server:
    logfile: "/var/log/unbound.log"
    log-time-ascii: yes
    module-config: "iterator"
    do-not-query-localhost: no
    interface: 127.0.1.1
    access-control: 127.0.0.0/8 allow
forward-zone:
   name: "."
   forward-addr: 127.0.0.1@53
   forward-first: no

remote-control:
       control-enable: no
```

Restart unbound and it should work.
